
@baseurl = http://localhost:8080/hogehoge-service


###
# GET
GET {{baseurl}}/api/greeting
Authorization: a
Accept: application/json

###
# GET
GET http://localhost:8080/hogehoge-service/api/greeting
Authorization: a
Accept: application/json

###
# GET
GET http://localhost:8080/hogehoge-service/hogehoge-service/sampleA/world

#### GET
GET http://localhost:8080/hogehoge-service/sampleA/hello

###

# GET
GET http://localhost:8080/sampleA/hello
###

# GET
GET http://localhost:8080/hogehoge-service/hogehoge-service/sampleA/hello
###


# GET
GET http://localhost:8080/hello


# GET
GET http://localhost:8080/sampleB/hello


###




# GET
GET http://localhost:8080/sampleA/world

###

# GET
GET http://localhost:8080/sampleB/hello

###

# GET
GET http://localhost:8080/sampleB/world
